# Generated by Django 2.2 on 2019-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=20)),
                ('apellidos', models.CharField(help_text='Apellidos de la persona', max_length=20)),
                ('edad', models.PositiveIntegerField(help_text='Edad de la persona', max_length=20)),
                ('fecha', models.DateField(help_text='Dia y mes del cumpleaños', max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
